services:
    _defaults:
        autowire: false
        autoconfigure: false

    ############################################################
    # Default Converter
    ############################################################
    default.converter:
        abstract: true
        class: Neusta\ConverterBundle\Converter\DefaultConverter

    ############################################################
    # Default Converter with Cache
    ############################################################
    default.converter.with.cache:
        abstract: true
        class: Neusta\ConverterBundle\Converter\DefaultCachedConverter
        decorates: default.converter
        arguments:
            $inner: '@.inner'

