services:
    _defaults:
        autowire: false
        autoconfigure: false

    ############################################################
    # Generic Converter
    ############################################################
    neusta_converter.generic_converter:
        abstract: true
        class: Neusta\ConverterBundle\Converter\GenericConverter

    ############################################################
    # Strategic Converter
    ############################################################
    neusta_converter.strategic_converter:
        abstract: true
        class: Neusta\ConverterBundle\Converter\StrategicConverter

    ############################################################
    # Populators
    ############################################################
    neusta_converter.mapped_property_populator:
        abstract: true
        class: Neusta\ConverterBundle\Populator\MappedPropertyPopulator

    neusta_converter.converting_populator:
        abstract: true
        class: Neusta\ConverterBundle\Populator\ConvertingPopulator
