services:
    _defaults:
        autowire: false
        autoconfigure: false

    ############################################################
    # Default Converter
    ############################################################
    neusta_converter.default_converter:
        abstract: true
        class: Neusta\ConverterBundle\Converter\DefaultConverter

    ############################################################
    # Strategic Converter
    ############################################################
    neusta_converter.strategic_converter:
        abstract: true
        class: Neusta\ConverterBundle\Converter\StrategicConverter

    ############################################################
    # Populators
    ############################################################
    neusta_converter.mapped_property_populator:
        abstract: true
        class: Neusta\ConverterBundle\Populator\MappedPropertyPopulator

    neusta_converter.converter_populator:
        abstract: true
        class: Neusta\ConverterBundle\Populator\ConverterPopulator
