services:
    _defaults:
        autowire: false
        autoconfigure: false

    ############################################################
    # Default Converter
    ############################################################
    default.converter:
        abstract: true
        class: Neusta\ConverterBundle\Converter\DefaultConverter
